Partial implementation of the homepage. More updates pending
Code-the-Dream-School/gg-pac-team7-front pull request #9
Opened 2024-09-08 23:10 UTC by tims139

2024-09-08 23:16 UTC, tims139 commented
It might be necessary to make it look nicer for the mobile version

2024-09-09 00:27 UTC, akhilwaghmare requested changes
Can you merge in the latest `main` branch to make sure you have the latest `.gitignore`? Other `.env` is being tracked, it should not be

2024-09-09 00:27 UTC, akhilwaghmare commented on .env
This should not be tracked by git. Make sure you merge in the latest `main`, which should include `.env` in the .gitignore file

2024-09-09 01:09 UTC, tims139 commented on .env
Done!

2024-09-09 19:41 UTC, akhilwaghmare approved these changes

2024-09-09 23:32 UTC, merged